services:
  raftainer:
    build: .
    env_file: .env
    volumes:
      - ../models:/models:ro
      - ./src:/app/src:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: npm run start:watch
