name: Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/raftainer/raftainer:latest .

    # Push the Docker image to GitHub Container Registry
    - name: Push the Docker image
      run: |
        docker push ghcr.io/raftainer/raftainer:latest
